### ISSUE TITLE
TW server using the LOLSKINMOD's problem

### ISSUE THREAD

**Issue by riory113** [moonshadow565/lolcustomskin#1]
would like to thank the producer for the program :)

There was no big problem with the US/KR server at the moment, but the friend who is using the TW server has a problem that cannot be executed like this way.

I think it is not possible to execute the answer due to a problem in the path. 
May I ask you to solve the problem?

![01](https://user-images.githubusercontent.com/52371983/60394700-9e374280-9b63-11e9-888e-73e4e937d86a.png)
![02](https://user-images.githubusercontent.com/52371983/60394701-9e374280-9b63-11e9-83b7-dac8074f3331.PNG)

**Comment by moonshadow565** [comment]
You are running league as admin.
