### ISSUE TITLE
 A very, very good mounter, but can it support Chinese servers?

### ISSUE THREAD

**Issue by rr4e** [moonshadow565/lolcustomskin#12]

**Comment by moonshadow565** [comment]
idk, you tell me?

**Comment by rr4e** [comment]
> idk, you tell me?

There is a free mounter in the local area, which is not open source and will be reported as a virus by the windows security center. It has been exposed to users to download Trojan horses to collect private information, push advertisements and install various bad software.
so ， Rubbish Native mounter .

**Comment by moonshadow565** [comment]
well i don't have chinese league installed so i wouldn't really know
assuming it works the same way as non-chinese league it should work just fine
just make sure you use english(ASCII) only folder names because league can't handle non-english(unicode) letters

**Comment by rr4e** [comment]
> well i don't have chinese league installed so i wouldn't really know
> assuming it works the same way as non-chinese league it should work just fine
> just make sure you use english(ASCII) only folder names because league can't handle non-english(unicode) letters


Thank you very much, I have tried to set the lol Android path to English C:\meapps\lol\Game many times, but the custom skin will not be mounted on the game.
![QQ截图20201127172814](https://user-images.githubusercontent.com/14058293/100433424-f93fd280-3092-11eb-86ac-a28b2c9d5e60.png)
And the command line is like this
![QQ截图20201127171508](https://user-images.githubusercontent.com/14058293/100433496-15dc0a80-3093-11eb-921c-8854ebf42d1d.png)
The same situation applies to Taiwan servers.
The previous Fantôme could be used in Southeast Asia, but it could not be used after the game was updated once.
and thank you very much

**Comment by moonshadow565** [comment]
If league is running with elevated privileges (as i assume is the case on asian servers) you will need to run tools as admin as well.
Here is a simple mod that should work: [](https://voxskins.com/yoru/bewitching-annie/)

**Comment by moonshadow565** [comment]
If this doesn't help.
Can you run game in windowed mode and screenshot title bar?

**Comment by rr4e** [comment]
Yes, every time I right-click the administrator to run, load Annie mod , and try to run in window
<img width="960" alt="11111" src="https://user-images.githubusercontent.com/14058293/100460125-95cb9a00-30be-11eb-9b99-802cfef47e19.png">

**Comment by moonshadow565** [comment]
So it does run as administrator.

Notice how in your first screenshot it couldn't even find league hence "Wait for league".
Meaning it couldn't even detect league is running.

Now it says "Wait for league to exit".
This means that:
1. it successfully found league
2. it successfully injected the payload into league

Where does chinese league download its files from?
Can you provide sha256 or any kind of checksum of "League of Legends.exe" ?

**Comment by rr4e** [comment]
yeah, 
This is the download address of the Chinese server lol official website

**Comment by moonshadow565** [comment]
It wants qq account or something so i'm affraid i can't download that.
If you want you can drop League of Legends.exe  + .dll's somewhere so i can check them out.
Preferably somewhere that doesn't require login or weird downloaders.

**Comment by rr4e** [comment]
yes，The ecology of this pretentious porcelain country always leads to the production of comic tools that are meaningless in themselves.

this is League of Legends.exe 
[League of Legends.zip](https://github.com/moonshadow565/lolcustomskin/files/5612214/League.of.Legends.zip)
and dll in the game root directory
https://drive.google.com/file/d/1nwJvtgmoFZVrageAhs-fOrw-tWLVHONx/view?usp=sharing
![QQ图片20201129213140](https://user-images.githubusercontent.com/14058293/100543302-3baa1080-3247-11eb-9901-ed95a6247ff1.png)

**Comment by moonshadow565** [comment]
Nothing much different happening there than non-chinese .exe.
Which leads me to believe the issue is either:
1. tencent AC interfering with WriteProcessMemory 
2. paths being different on chinese installation

If you are able to compile this yourself 1. should be easy to check.
Reading back after writing here:
[https://github.com/moonshadow565/lolcustomskin/blob/master/src/process.cpp#L197](https://github.com/moonshadow565/lolcustomskin/blob/master/src/process.cpp#L197)
and checking if read bytes match written ones should hopefully do the trick

2. wouldn't mean simply that non-chinese mods wouldn't work on chinese installation
Does chinese league have "Game/DATA/FINAL/Champions/Annie.wad.client" ?

**Comment by rr4e** [comment]
yes ,he have 
![QQ截图20201201093005](https://user-images.githubusercontent.com/14058293/100685715-cb011200-3374-11eb-9571-bf78ebffbc78.png)

**Comment by rr4e** [comment]
Thank you very much, I will study it
