### ISSUE TITLE
I can't patch .bnk (Sound) file into the game

### ISSUE THREAD

**Issue by MoriKamiya** [moonshadow565/lolcustomskin#3]
I can't patch .bnk  file (Sound data) into the game, but other file like .skl, .skn .dds etc. can patch.
Is that normal?

**Comment by moonshadow565** [comment]
You will probably need to patch those with custom .wad's

**Comment by moonshadow565** [comment]
https://github.com/moonshadow565/lolcustomskin-tools/wiki
