### ISSUE TITLE
Hi I'm gonna ask you a few questions.

### ISSUE THREAD

**Issue by xotjrrjseka** [moonshadow565/lolcustomskin#5]
Hi, I am xotjrjseka1 and I tried to apply your lol nude skin mod, but I failed to do that so I want to ask you some questions. First, all 3 files you uploaded in your :C/skin/lolskinmodfolder should be unzipped? And we can create a new folder called "mod" in the game folder of legions, decompress the files in the mega, and then run lolcustomskin.exe?

**Comment by moonshadow565** [comment]
i do not have any mods you should ask mod author for help...
