### ISSUE TITLE
No Checksum/Failed to open process

### ISSUE THREAD

**Issue by bokuwaTel** [moonshadow565/lolcustomskin#6]
Hi, uh, I saw a previous issue along the same lines, but I thought that (since I **am**, in fact, using Windows 10) this would be different.
My issue is quite the same, however on my command prompt it seems to completely lack a checksum altogether. See for yourself:
![im confused pls halp](https://user-images.githubusercontent.com/36824334/65362144-eea2c700-dbcb-11e9-8358-95c896ca52f5.PNG)

I  followed every last bit of your guide on "how to" the exact way it was written, I've tried re-downloading the patcher entirely, yet the problem persists. I'm perplexed. Perhaps I'm just stupid. lol

EDIT: Resolved by user - should have probably tried this first, but my day was stressful and my brain was offline. Run the program as an administrator.

**Comment by moonshadow565** [comment]
You are running **league of legends** as administrator.
You shouldn't do that , you will have to go to your league folder and strip admin priv from all .exe's by right clicking them then going to properties.
